### ISSUE TITLE
Implement dynamic card generation

### ISSUE THREAD

**Issue by rhendz** [vjsrinivas/potify#13]
On the home page and past work orders page, cards should be dynamically added.

Upon initial loading, there should be no cards present. Instead, they are loading in dynamically by checking the current JSON file (depends on Firebase integration) and picking up to 5-10 of the highest priority work orders / most recently completed work orders.

This will require utilizing TypeScript and parsing JSON.

**Comment by rhendz** [comment]
This will probably utilize [structural directives](https://angular.io/guide/structural-directives).

**Comment by vjsrinivas** [comment]
Feature has been added with workGenerate branch merge.
